import { Project } from '../types';

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-viral-podcast-1',
    name: 'Founders Deep Dive: Scaling to $10M ARR',
    videoUrl: '/api/videos/sample-podcast.mp4',
    videoDuration: 30,
    fileSize: 18 * 1024 * 1024,
    createdAt: new Date(Date.now() - 3600 * 1000 * 24 * 2).toISOString(),
    thumbnailUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&auto=format&fit=crop&q=80',
    clips: [
      {
        id: 'clip-p1-1',
        title: 'YOU WON\'T BELIEVE WHAT HAPPENS NEXT! 😱',
        alternativeTitles: [
          'The Brutal Truth About Scaling Fast',
          'Why 90% of Startups Run Out of Cash',
          'The 60-Second Advice That Changed Everything',
          'Stop Overcomplicating Your Business Model',
        ],
        startTime: 1.0,
        endTime: 12.5,
        duration: 11.5,
        viralityScore: 96,
        hook: 'Watch closely because the moment this happens, everything changes.',
        alternativeHooks: [
          'If you run any business in 2026, stop scrolling right now.',
          'This is the one mistake that quietly bankrupts founders.',
          'Most people wait years to learn this hard lesson.',
        ],
        reason: 'Explosive contrarian hook with immediate tension and high emotional retention.',
        subjectTrack: [
          { time: 1.0, focusX: 0.5 },
          { time: 6.0, focusX: 0.48 },
          { time: 12.0, focusX: 0.52 },
        ],
        captions: [
          {
            id: 'cap-p1-1',
            start: 1.2,
            end: 5.8,
            text: 'MOST PEOPLE NEVER REALIZE THIS UNTIL IT IS TOO LATE',
            words: [
              { word: 'MOST', start: 1.2, end: 1.6 },
              { word: 'PEOPLE', start: 1.6, end: 2.1 },
              { word: 'NEVER', start: 2.1, end: 2.6 },
              { word: 'REALIZE', start: 2.6, end: 3.2 },
              { word: 'THIS', start: 3.2, end: 3.6 },
              { word: 'UNTIL', start: 3.6, end: 4.1 },
              { word: 'IT', start: 4.1, end: 4.4 },
              { word: 'IS', start: 4.4, end: 4.8 },
              { word: 'TOO', start: 4.8, end: 5.2 },
              { word: 'LATE', start: 5.2, end: 5.8 },
            ],
          },
          {
            id: 'cap-p1-2',
            start: 6.0,
            end: 11.8,
            text: 'WHEN YOU SHIFT YOUR FOCUS EVERYTHING ELSE EXPANDS RAPIDLY',
            words: [
              { word: 'WHEN', start: 6.0, end: 6.4 },
              { word: 'YOU', start: 6.4, end: 6.8 },
              { word: 'SHIFT', start: 6.8, end: 7.3 },
              { word: 'YOUR', start: 7.3, end: 7.7 },
              { word: 'FOCUS', start: 7.7, end: 8.3 },
              { word: 'EVERYTHING', start: 8.3, end: 9.1 },
              { word: 'ELSE', start: 9.1, end: 9.6 },
              { word: 'EXPANDS', start: 9.6, end: 10.4 },
              { word: 'RAPIDLY', start: 10.4, end: 11.2 },
            ],
          },
        ],
        social: {
          description: 'The real secret to high growth isn\'t working more hours—it\'s eliminating the wrong priorities. Let us know if this resonated! 👇🔥',
          hashtags: ['#shorts', '#viral', '#founder', '#startups', '#business', '#mindset'],
          keywords: ['scaling', 'startups', 'entrepreneurship', 'productivity'],
          youtube: 'Stop overworking and start focusing. Drop your thoughts below! 👇\n\n#shorts #startups #growth #viral',
          tiktok: 'Save this video before your next work session! 💡🔥 #fyp #entrepreneur #wealth #mindsetshift',
          instagram: 'The biggest leverage in business is knowing what NOT to do.\n\nSave & share with someone building something big! 📌\n\n#reels #growthmindset #businessowner #founderlife',
          linkedin: 'A pivotal takeaway on decision fatigue and organizational focus for modern leaders.',
        },
        aspectRatio: '9:16',
        captionPreset: 'bold',
        customSticker: '🔥',
        customCropX: 0.5,
        playbackSpeed: 1,
      },
      {
        id: 'clip-p1-2',
        title: 'The Most Unexpected Moment of the Interview',
        alternativeTitles: [
          'Why Perfectionism Is A Trap',
          'How To Overcome Self-Doubt Instantly',
          'The Rule of 100 Repetitions',
          'Watch What Happens When You Commit',
        ],
        startTime: 3.5,
        endTime: 14.0,
        duration: 10.5,
        viralityScore: 91,
        hook: 'I tested this rule for 30 days and the results were shocking.',
        alternativeHooks: [
          'What happens when you stop seeking approval?',
          'Here is the exact truth behind consistency.',
          'You need to hear this before tomorrow morning.',
        ],
        reason: 'Fast-paced storytelling that builds curiosity and delivers actionable value.',
        subjectTrack: [
          { time: 3.5, focusX: 0.5 },
          { time: 8.0, focusX: 0.52 },
          { time: 13.5, focusX: 0.49 },
        ],
        captions: [
          {
            id: 'cap-p1-3',
            start: 3.8,
            end: 8.5,
            text: 'CONSISTENCY BEATS TALENT EVERY SINGLE DAY OF THE WEEK',
            words: [
              { word: 'CONSISTENCY', start: 3.8, end: 4.6 },
              { word: 'BEATS', start: 4.6, end: 5.1 },
              { word: 'TALENT', start: 5.1, end: 5.7 },
              { word: 'EVERY', start: 5.7, end: 6.2 },
              { word: 'SINGLE', start: 6.2, end: 6.8 },
              { word: 'DAY', start: 6.8, end: 7.3 },
              { word: 'OF', start: 7.3, end: 7.6 },
              { word: 'THE', start: 7.6, end: 7.9 },
              { word: 'WEEK', start: 7.9, end: 8.4 },
            ],
          },
          {
            id: 'cap-p1-4',
            start: 8.8,
            end: 13.5,
            text: 'SHOW UP REGARDLESS OF HOW YOU FEEL IN THE MOMENT',
            words: [
              { word: 'SHOW', start: 8.8, end: 9.3 },
              { word: 'UP', start: 9.3, end: 9.7 },
              { word: 'REGARDLESS', start: 9.7, end: 10.6 },
              { word: 'OF', start: 10.6, end: 10.9 },
              { word: 'HOW', start: 10.9, end: 11.3 },
              { word: 'YOU', start: 11.3, end: 11.6 },
              { word: 'FEEL', start: 11.6, end: 12.1 },
              { word: 'IN', start: 12.1, end: 12.4 },
              { word: 'THE', start: 12.4, end: 12.7 },
              { word: 'MOMENT', start: 12.7, end: 13.3 },
            ],
          },
        ],
        social: {
          description: 'Talent without discipline is wasted potential. Drop a 💯 if you agree!',
          hashtags: ['#shorts', '#discipline', '#motivation', '#habits', '#viral'],
          keywords: ['habits', 'success', 'mindset', 'focus'],
        },
        aspectRatio: '9:16',
        captionPreset: 'impact',
        customSticker: '⚡',
        customCropX: 0.5,
        playbackSpeed: 1,
      },
    ],
  },
  {
    id: 'proj-keynote-tech-2',
    name: 'Future of Spatial Interfaces & Autonomous AI',
    videoUrl: '/api/videos/sample-tech.mp4',
    videoDuration: 30,
    fileSize: 24 * 1024 * 1024,
    createdAt: new Date(Date.now() - 3600 * 1000 * 24 * 5).toISOString(),
    thumbnailUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&auto=format&fit=crop&q=80',
    clips: [
      {
        id: 'clip-p2-1',
        title: 'The AI Shift That Will Catch Everyone Off Guard 🤯',
        alternativeTitles: [
          'Why Traditional Apps Are Going Extinct',
          'The Autonomous Agent Revolution',
          'How Spatial Computing Replaces Smartphones',
          'Prepare For The Biggest Tech Pivot Yet',
        ],
        startTime: 0.5,
        endTime: 13.0,
        duration: 12.5,
        viralityScore: 94,
        hook: 'We are about to witness the fastest technological transition in human history.',
        alternativeHooks: [
          'If you build software, this will change your roadmaps permanently.',
          'Here is what hardware looks like 3 years from today.',
          'Nobody is ready for what comes next.',
        ],
        reason: 'High-concept technological prediction with massive curiosity appeal.',
        subjectTrack: [
          { time: 0.5, focusX: 0.5 },
          { time: 7.0, focusX: 0.51 },
          { time: 13.0, focusX: 0.5 },
        ],
        captions: [
          {
            id: 'cap-p2-1',
            start: 0.8,
            end: 6.2,
            text: 'WE ARE MOVING BEYOND STATIC SCREENS INTO LIVING SPACES',
            words: [
              { word: 'WE', start: 0.8, end: 1.1 },
              { word: 'ARE', start: 1.1, end: 1.4 },
              { word: 'MOVING', start: 1.4, end: 2.1 },
              { word: 'BEYOND', start: 2.1, end: 2.7 },
              { word: 'STATIC', start: 2.7, end: 3.3 },
              { word: 'SCREENS', start: 3.3, end: 4.1 },
              { word: 'INTO', start: 4.1, end: 4.6 },
              { word: 'LIVING', start: 4.6, end: 5.3 },
              { word: 'SPACES', start: 5.3, end: 6.1 },
            ],
          },
          {
            id: 'cap-p2-2',
            start: 6.6,
            end: 12.4,
            text: 'INTELLIGENCE WILL BLEND INVISIBLE IN THE WORLD AROUND US',
            words: [
              { word: 'INTELLIGENCE', start: 6.6, end: 7.6 },
              { word: 'WILL', start: 7.6, end: 8.0 },
              { word: 'BLEND', start: 8.0, end: 8.6 },
              { word: 'INVISIBLE', start: 8.6, end: 9.6 },
              { word: 'IN', start: 9.6, end: 9.9 },
              { word: 'THE', start: 9.9, end: 10.2 },
              { word: 'WORLD', start: 10.2, end: 10.8 },
              { word: 'AROUND', start: 10.8, end: 11.5 },
              { word: 'US', start: 11.5, end: 12.2 },
            ],
          },
        ],
        social: {
          description: 'Are you ready for the post-smartphone era? Share your thoughts below! 👇🤖',
          hashtags: ['#shorts', '#tech', '#future', '#ai', '#innovation', '#viral'],
          keywords: ['spatial computing', 'future tech', 'artificial intelligence'],
        },
        aspectRatio: '9:16',
        captionPreset: 'neon',
        customSticker: '🚀',
        customCropX: 0.5,
        playbackSpeed: 1,
      },
    ],
  },
];
